---
search:
    keywords: ['exception','finally','异常']

---


# 给定下面代码片段

```java
try {
	method();
	System.out.println("Hello World");
} catch (ArrayIndexOutOfBoundsException e) {
	System.out.println("Exception1");
} catch (Exception e) {
	System.out.println("Exception2");
} finally{
	System.out.println("Think You");			
}
```
#　如果method抛出一个NullPointerException的异常，会显示( )

A. Hello World   
B. Exception1  
C. Exception2  
D. Think You

# 参考答案

C,D;
如果method抛出一个NullPointerException的异常,则会被Exception捕获，显示Exception2，finally语句块一定会执行，显示Think You。System.out.println("Hello World");在异常发生之后，不会执行，即A不会显示，未捕获到ArrayIndexOutOfBoundsException，B选项不会打印。

---